auto_prepend_file = ../vercel_session.php
session.save_path = /tmp
session.gc_maxlifetime = 86400
session.cookie_lifetime = 86400
session.cookie_httponly = 1
session.cookie_secure = 1
session.cookie_samesite = "Lax"
display_errors = Off
log_errors = On
error_log = /tmp/php-error.log
